### ISSUE TITLE
About modal

### ISSUE THREAD

**Issue by Misjohns** [instructlab/ui#102]
InstructLab needs an about modal to display information about the application. The user will access this modal from the Help menu on the masthead. About modal should include the following:
- product version number(s)
- appropriate legal text

Reference: https://www.patternfly.org/components/about-modal/design-guidelines

@beaumorley

**Comment by Misjohns** [comment]
Who can provide the version and legal content for this page?

**Comment by Misjohns** [comment]
### Design
![image](https://github.com/user-attachments/assets/0196721e-fe12-4ee5-970c-254b46c617a0)


### About model content

Headline: 
About InstructLab

Description: 
InstructLab is an open source AI project that allows you shape the future of Large Language Models. Join the community to start contributing today.

Button:
(fa-github icon) Join the community

Links: 
instructlab.ai (https://instructlab.ai/)
Collaborate (https://github.com/instructlab/community/blob/main/Collaboration.md)
Code of Conduct (https://github.com/instructlab/community/blob/main/CODE_OF_CONDUCT.md)
Sponsored by Red Hat (https://www.redhat.com)

Copyright:
© InstructLab

**Comment by Misjohns** [comment]
We need to include version details in the About modal. @vishnoianil can you provide this information?

**Comment by Misjohns** [comment]
Added version to design. Just need someone to verify the version and format we should display.


![Image](https://github.com/user-attachments/assets/555d840b-3cfd-49cc-8edb-7afccd1006cd)

**Comment by itspatys** [comment]
Hi! May I help on implementing that?

**Comment by vishnoianil** [comment]
@itspatys Absolutely!, I am trying to get "terms of service" and "Private policy" text to add to the login page, once i have those I can share it with you, but meanwhile feel free to hack on it. Ping us in the UI slack channel in instructlab worksspace if you have any question regarding dev environment setup etc.

**Comment by itspatys** [comment]
@Misjohns could you provide or point me to the background image? the on in the designs is slightly different than `InstructLab-Background-Image.png`

**Comment by Misjohns** [comment]
@itspatys Let me know if you need a different format or saved in a different manner
[
![InstructLab-About](https://github.com/user-attachments/assets/cf6f1142-9063-4f4a-a2dd-c5e4d8ec0c53)
![InstructLab-About](https://github.com/user-attachments/assets/895c81b0-31b0-49da-9648-2d5366a12db7)
](url)

**Comment by itspatys** [comment]
@Misjohns, that's perfect, thanks!
