### ISSUE TITLE
Promote Ash Evans to a Maintainer role for UI project

### ISSUE THREAD

**Issue by vishnoianil** [instructlab/ui#104]
*For details on how this process works, please see our [contributor roles documentation](https://github.com/instructlab/community/blob/main/CONTRIBUTOR_ROLES.md)*

**Which member are you nominating for a team change?**
Ash Evans - @aevo98765 

**Current active maintainers sponsoring this nomination for the promotion?**
@vishnoianil @nerdalert 

**Make your case here: Why should the nominated member be on the UI team?**

@aevo98765 is a rock star and made significant contributions to the project in term of contributing new UI features, fixing/raising/triaging issues, contributing and review code, actively participating in the design discussions, community discussions and upstream project meetings. Apart from that he is actively helping the project in building a healthy community by spreading words about the project work and bringing more interested contributor to the project. He brings 

His current contributions can be seen here: 
[Pull Requests Authored](https://github.com/instructlab/ui/pulls?q=is%3Apr+author%3Aaevo98765+) / [Pull Requests Reviewed](https://github.com/instructlab/ui/pulls?q=is%3Apr+reviewed-by%3Aaevo98765+) / [Issues Created](https://github.com/instructlab/ui/issues?q=is%3Aissue+author%3Aaevo98765+)

Due to his excellent overall contribution to the project and upstream community, i would like to nominate @aevo98765 for the maintainer role.

cc @nerdalert

**Comment by vishnoianil** [comment]
@nerdalert @renrenstart @russellb @juancappi @chungtan @toraponibm Please provide +1/0/-1 on the nomination above, so that we can conclude the nomination. Thanks!

**Comment by vishnoianil** [comment]
+1

**Comment by juancappi** [comment]
+1

**Comment by nerdalert** [comment]
+1 🥳

**Comment by vishnoianil** [comment]
More than 50% maintainers provided +1 and no objection from other maintainers, so considering this nomination approved. 

Congratulations!! @aevo98765 for first maintainer approved through the maintainer promotion process. Really appreciate you stepping up for helping maintainers to steer the project.

**Comment by vishnoianil** [comment]
@aevo98765 is promoted to project maintainer and all the required permissions are granted. This concludes the nomination.
