### ISSUE TITLE
Decouple from GitHub

### ISSUE THREAD

**Issue by mairin** [instructlab/ui#106]
Not all instructlab usages are so dependent on GitHub. For example, some instructlab usage uses branches instead of GitHub PRs to signify nodes. 

Ideally using GitHub would be one option and the UI would have another option to support disconnected use cases / the branch use case. 

See https://instruct-lab.slack.com/archives/C076C9RNKSA/p1722603423076369?thread_ts=1722537439.630099&cid=C076C9RNKSA for more context.

**Comment by vishnoianil** [comment]
This enhancement is addressed through #412
