### ISSUE TITLE
Validate that the YAML outputted from the Knowledge form is compatible with version 3

### ISSUE THREAD

**Issue by aevo98765** [instructlab/ui#113]
https://github.com/instructlab/taxonomy/blob/main/README.md#knowledge-yaml-examples

Acceptance Criteria:

Fill out the knowledge submission form.

Download the YAML.

Check that it matches the required YAML format that is outlined on the README link above.

**Comment by aevo98765** [comment]
Need https://github.com/instructlab/ui/pull/111 to be merged.

**Comment by vishnoianil** [comment]
PR #111 and PR #138 covers all the knowledge v3 schema constraints.
 @aevo98765 Closing this issue, but if you see any missing schema constraints that is not enforced, please feel free to open a specific issue to track that. Thanks!
