### ISSUE TITLE
Knowledge and Skills contribution form buttons should be disabled by default

### ISSUE THREAD

**Issue by Misjohns** [instructlab/ui#120]
The buttons at the bottom of the Knowledge and Skill contribution forms should appear disabled until some portion of the form is entered. We need to identify the required fields and those items should be completed until these buttons are active.

<img width="583" alt="Screenshot 2024-08-16 at 1 04 31 PM" src="https://github.com/user-attachments/assets/7cd037fc-c165-4e28-951d-815962106ea6">

**Comment by vishnoianil** [comment]
Fixed through #138
