### ISSUE TITLE
Can you guide me how to launch/run the instruct lab UI?

### ISSUE THREAD

**Issue by MAhmadUzair** [instructlab/ui#122]
I have worked with instructlab CLI based, Now I want to run the UI. Is there any full guide that can show me how to run the instructlab UI?

**Comment by aevo98765** [comment]
Hi @MAhmadUzair, thanks for showing interest in the UI repo!

If you are a developer then docs/development.md will have instructions of how you can run the UI. 
This will require you to:
1) have Node installed on your machine.
2) Create a .env file with oauth creds @vishnoianil can help with this.

If not we do have a deployed QA UI which you could just access from your browser. @vishnoianil and @nerdalert can direct you to this one.

Let us know your preference and how you would want to get involved.

**Comment by vishnoianil** [comment]
@MAhmadUzair Please join the community UI slack channel (instructions : https://github.com/instructlab/ui?tab=readme-ov-file#contributing). Most of the contributor hangout in the "UI" channel, and probably a faster way to resolve issues related to dev environment setup etc.
