### ISSUE TITLE
Improve from elements across GUI

### ISSUE THREAD

**Issue by Misjohns** [instructlab/ui#149]
**Existing implementation**
Current implementation creates clutter and makes association of field validation confusing.

![image](https://github.com/user-attachments/assets/3ad71305-2052-45f2-9411-66b281c61ac2)

**UX recommendation**

- Supplement field level errors with an inline alert placed below the form’s header and description. This makes it any for the user to quickly identify areas that need attention. 
- Display an error icon on collapsed field groups to indicate hidden field level errors.
- Always provide labels for text and data inputs so that users understand the information each form field even when the field is populated. The PF form layout allows for enough horizontal space between fields for intuitive helper text and validation messaging.
- If a user leaves a required field empty or incomplete, use a field level error message to communicate the error in a consistent and concise manner: “Required field”.

[Inline Alert in Horizontal Form](https://www.patternfly.org/components/alert/html-demos/inline-alert-in-horizontal-form/) | [PF Form Guidelines](https://www.patternfly.org/components/forms/form/design-guidelines#errors-and-validation)

![image](https://github.com/user-attachments/assets/004b3e78-3e40-4a74-906b-3e64d9c01411)

**Comment by ashapadmashetti** [comment]
I am working on this issue. Can someone assign it to me

**Comment by ashapadmashetti** [comment]
@Misjohns I made this initial draft for the column gap and the labels. Could you please let me know if this is what is expected?
<img width="1065" alt="image" src="https://github.com/user-attachments/assets/049d2ccb-b698-4d5f-b646-586455b9bb63">

**Comment by Misjohns** [comment]
LGTM @ashapadmashetti Thank you
