### ISSUE TITLE
Improve the experience for entering documents information

### ISSUE THREAD

**Issue by toraponibm** [instructlab/ui#150]
Each knowledge contribution should have the `document` information, which points to (1) a specific github repo and commit hash, and (2) a list of document files (described as patterns).
See https://github.com/instructlab/taxonomy?tab=readme-ov-file#getting-started-with-knowledge-contributions on more details.

With this in mind, when creating a new knowledge contribution on UI, the user can upload document files, which automatically creates both (1) and (2) above.
- The suggested improvement here is to show the list of uploaded files (before the contribution submission). Adopt a common file upload component pattern if it fits.
- On top of that, allow the user to delete some files from the list.
    + A development note: the uploaded files don't have to be deleted from the git repo, just file petterns need to reflect the edit.
- Also, allow the second files upload, to "append" to the existing list.
    + A development note: The commit hash from the last files upload should be used

When viewing and editing an existing knowledge contribution on UI,
- As with the above case, show the list of document files (file name patterns)
- Allow the user to delete some files from the list, and allow the user to do an additional files upload

**Comment by vishnoianil** [comment]
This issue is also tracked through #152 . #152 has more details around the possible UI mockup that we can use. 

Duplicate #152 
Closing this issue. @toraponibm if you think we can use this to track any specific aspect of this document handling feature, please feel free to re-open the issue and update the issue description with details. Thanks!
