### ISSUE TITLE
Outputted qna.yml has new lines within context and question and answers 

### ISSUE THREAD

**Issue by aevo98765** [instructlab/ui#157]
Linked to https://github.com/instructlab/ui/issues/113
When I create a qna.yaml via the UI new lines are undesirably introduced into document outline, context and question and answer sections.

I am not 100% sure that this will have a detrimental effect on the users submission. However, this is not desirable behaviour and for completeness and consistency this should be corrected.

Acceptance Criteria:

- Ensure that the outputted qna.yaml does not have new lines with the document outline, context and question answers.

<img width="682" alt="Screenshot 2024-09-06 at 10 53 47" src="https://github.com/user-attachments/assets/f46654a3-3fdb-4acf-8366-a61330d776c9">

**Comment by aevo98765** [comment]
I have highlighted this as an issue. However i think it is a consequence of a user copying and pasting content which already has pre-defined /n (new line) characters. This does not match the width of the input boxes and therefore looks unsightly. However I am wondering if this would have any ACTUAL impact on user experience @nerdalert @vishnoianil ??

**Comment by vishnoianil** [comment]
I think first thing we need to ensure is that it doesn't fail the yaml linter. If it does, that's a bug and we need to fix it. 

From UX perspective, i think we should parse the text to remove these new lines. I don't think it has any impact as such when it comes to training/generation with ilab. Something similar to removing the trailingspaces here would be helpful https://github.com/instructlab/ui/blob/main/src/utils/yamlConfig.ts#L58

**Comment by aevo98765** [comment]
I can't replicate this anymore and are therefore closing this issue.
