### ISSUE TITLE
No created_by data in the qna.yaml file

### ISSUE THREAD

**Issue by aevo98765** [instructlab/ui#158]
At present the outputted qna.yaml file from knowledge submission has a blank created_by field. This should be populated with the username of the person submitted or they could override and add another name for submission.

Acceptance Criteria:

- The created_by section of the qna.yaml file should be populated.
<img width="661" alt="Screenshot 2024-09-06 at 10 57 45" src="https://github.com/user-attachments/assets/e1f447b7-66a5-4a37-9ef4-0626b42aef07">

**Comment by vishnoianil** [comment]
I recently updated the qa.ui.instructlab.ai, and i don't see this issue in this version. It's been address with knowledge/skill edit refactoring patches. Here is the example from the latest version running in QA

https://github.com/instructlab-public/test-taxonomy/pull/78/files

**Comment by vishnoianil** [comment]
@aevo98765 closing this issue, but if you see the issue again with the latest code, please feel free to re-open the issue.
