### ISSUE TITLE
Improve responsive experience of Login

### ISSUE THREAD

**Issue by Misjohns** [instructlab/ui#164]
Need to improve the responsive experience so it responds to changes in browser width by adjusting the placement of design elements to fit in the available space.

At 375 x 667
<img width="516" alt="Screenshot 2024-09-09 at 3 51 04 PM" src="https://github.com/user-attachments/assets/af700b7f-9911-4a3d-80a2-a5a386d431ed">

At 1024x768
<img width="1026" alt="Screenshot 2024-09-09 at 3 50 08 PM" src="https://github.com/user-attachments/assets/dd066b8f-fd72-48ae-a395-e7f07828b462">

Currently, some elements get hidden as the window size changes.
<img width="517" alt="Screenshot 2024-09-09 at 4 02 09 PM" src="https://github.com/user-attachments/assets/178def90-d233-4309-83c3-190fde05fdc8">

**Comment by samarpita-bhaumik** [comment]
I will be working on this issue

**Comment by samarpita-bhaumik** [comment]
This issue is fixed from my side. The merged Pull request is: https://github.com/instructlab/ui/pull/216.
