### ISSUE TITLE
Improve responsive behavior of Header and Side Navigation Bar

### ISSUE THREAD

**Issue by ediazgallego** [instructlab/ui#194]
## Existing Implementation
The header and left sidebar of the application are not responsive, causing layout issues and reduced usability on smaller window sizes and mobile devices

![Screenshot 2024-09-23 142448](https://github.com/user-attachments/assets/6afa0124-1f40-4d36-88c1-399d0adced56)
![Screenshot 2024-09-23 142504](https://github.com/user-attachments/assets/9f1c84fd-0881-44d0-8b3b-ce876706c5ae)
![Screenshot 2024-09-23 142517](https://github.com/user-attachments/assets/ea727405-6563-4d73-a5af-033a535d34dd)

You can refer to this [PatternFly demo](https://www.patternfly.org/patterns/dashboard/html-demos/basic/) as an example of correct responsiveness for the header and left sidebar, which could serve as a possible solution.

**Comment by vishnoianil** [comment]
@ediazgallego Absolutely! Sounds good to me.
