### ISSUE TITLE
[FEAT] PDF to Markdown convert

### ISSUE THREAD

**Issue by Gregory-Pereira** [instructlab/ui#2]
It would be nice to have a feature to enable user file uploads and conversion of PDF to markdown. This would enable us to iterate on the UX of submitting your own Taxonomy, as well as it could be leveraged to improve the Triager experience creating and auditing QNA submissions.

More info: https://instruct-lab.slack.com/archives/C076C9RNKSA/p1718381515763659

/cc @nerdalert @mingxzhao @vishnoianil

**Comment by vishnoianil** [comment]
@Gregory-Pereira Let's track this through #137. is it okay to close this issue?
