### ISSUE TITLE
Create a template repo in upstream for forking for knowledge store and reference

### ISSUE THREAD

**Issue by nerdalert** [instructlab/ui#20]
- We need a template repo for knowledge document submissions in instructlab.
- This will allow for users to upload docs by automating the fork and uploading, PR, SHA retrieval by the UI. It also satisfies the constraint to not store documents themselves in upstream for liability reasons.
- This will probably require a dev-doc submission to get a repo cut in the UI directory there.
- See workflow:

![Knowledge-Submission-v2](https://github.com/instructlab/ui/assets/1711674/08f052f1-d874-4f9c-8438-a674ffc2530f)

**Comment by Gregory-Pereira** [comment]
I am going to add this awesome drawing to the docs directory so it gets persisted past just an issue that will eventually get resolved. Aside from this we can close this out, WDYT @nerdalert?

**Comment by vishnoianil** [comment]
Required repository is created and already in use with test-taxonomy repo. https://github.com/instructlab-public/taxonomy-knowledge-docs

@nerdalert closing this issue, but feel free to re-open it if you think it has any pending todo.
