### ISSUE TITLE
Define the deployment pieces required for a local deployment

### ISSUE THREAD

**Issue by nerdalert** [instructlab/ui#223]
Currently the project is deployed as a SaaS. We need to identify a plan to make all of the components function in a local environment.

Need to decouple dependancies in:
- Local Auth.
- Move from Github to git.
- Chat endpoints need to be local only if service endpoints are not defined.

**Comment by vishnoianil** [comment]
Some of the self-hosted version of git can be explored as well for local deployments;

https://about.gitea.com/products/gitea/
https://github.com/go-gitea/gitea
https://github.com/gogs/gogs?tab=MIT-1-ov-file
https://gogs.io/
https://forgejo.org/

**Comment by vishnoianil** [comment]
This enhancement is done through #314 and #412
