### ISSUE TITLE
Add some basic Playwright UI tests

### ISSUE THREAD

**Issue by nerdalert** [instructlab/ui#23]
Feel free to ping @nerdalert for how to start with this. I will do it if no one picks it up.

**Comment by vishnoianil** [comment]
@aevo98765 Just pinging in case you are interested in it.

**Comment by adigidh** [comment]
Is anyone actively working on this issue? Can I pick this up if this isn't under anyone's ownership yet?

**Comment by aevo98765** [comment]
Not picked it up yet. Feel free to pick this up if you want!

**Comment by adigidh** [comment]
Thanks @aevo98765 . I can work on this one, will take a first pass at opening a PR for this work :)

**Comment by vishnoianil** [comment]
@adigidh Please let me know if you are hacking on this one? I can assign the issue to you.

I bumped the priority of this issue and also promoted it from backlog to ready, given that we are about to officially release our UI release, and these tests can be helpful to keep the sanity check of the release as well as avoid the regression.

**Comment by adigidh** [comment]
@vishnoianil : I was getting ready to setup my local dev environment, but was facing errors with respect to some npm packages, and .env file. Slack DM-ing you now..

Yes basic tests should be do-able. Going to take a first pass at this issue during this week.
