### ISSUE TITLE
Improve the user experience for knowledge "Submit File" 

### ISSUE THREAD

**Issue by vishnoianil** [instructlab/ui#236]
In following scenarios it can take a while for "Submit File" in knowledge form to finish the task:
- local clone of [texonomy-knowledge-doc repo](https://github.com/instructlab-public/taxonomy-knowledge-docs) 
- want to upload large size file or 
- want to upload multiple files

Currently UI doesn't notify anything to user about the work-in-progress. It directly shows the success or failure once the task is done. For a better user experience, UI should show the message with a spinner notifying that the upload is currently in progress.

**Comment by nikhil-krajput** [comment]
I would like to work on this , could you assign this to me

**Comment by vishnoianil** [comment]
@nikhil-krajput done, welcome aboard. If you need any help with setting up your local dev environment, please join instructlab slack workspace and ping folks on #ui channel. You can find more details here : https://github.com/instructlab/ui?tab=readme-ov-file#contributing

**Comment by vishnoianil** [comment]
Issue is fixed through #431
