### ISSUE TITLE
Adding ability to download partially completed knowledge and Skill forms

### ISSUE THREAD

**Issue by mingxzhao** [instructlab/ui#240]
At the moment it appears that when a knowledge or skill submission is not fully filled in, you are unable to submit or download. While this makes sense for submissions, there would likely be cases where users may want to download a partially completed yaml file for submission. Once such case would be to save their progress on yaml creation to be able to finish creation at a later point in time. 
This allows for those creating more complex contributions, particularly with the current complexity of knowledge submissions, to save their work for future completion.

**Comment by vishnoianil** [comment]
This has been discussed in one of the upstream community UI meeting. The high level idea was to allow user to save and resume their work (skill or knowledge or chat logs). Next release we are planning to integrate the backend storage where we can store these intermediate workflow states.

**Comment by aevo98765** [comment]
@vishnoianil does this mean that we won't be implementing this issue? yes -> I will close. no -> I will assign to myself.

**Comment by vishnoianil** [comment]
> I do still believe this is a good enhancement to have. Beyond reducing the immediate need for backend store, it also allows users to have an easier way to collaborate on yamls, if I were to want to start a yaml and have someone else review/finish, it would be nice to not have to go through and fill all blanks before I could download and send.

I think for short term this solution makes sense. @aevo98765 can you enable both download and view buttons by default. 

For long term, I think peer review use case is interesting and i think it might occur more frequently in practice. @mingxzhao I am thinking of providing a collaboration feature where one user can add another user as a collaborator of the skill/knowledge form. Collaborator will be able to see the shared skill/knowledge contribution on the dashboard and should be able to edit and submit as well (Mostly like PR collaborator, but without complicated git commands, and scoped for knowledge and skill forms). wdyt?
cc: @nerdalert @jjasghar @juliadenham

**Comment by aevo98765** [comment]
https://github.com/instructlab/ui/pull/255
