### ISSUE TITLE
Cancel fetch PRs if user login with admin/password in dev

### ISSUE THREAD

**Issue by vodnalasricharan** [instructlab/ui#242]
Presently if we login with admin credentials in **dev**, it is trying to fetch PR's this should not happen

![Screenshot 2024-10-04 at 8 58 37 AM](https://github.com/user-attachments/assets/1e254fb6-5720-4851-a185-71635ac71daf)

**Comment by dajana212** [comment]
Hello, I would like to work on this issue, can you assign it to me?

**Comment by vishnoianil** [comment]
> @dajana212 Please feel free to assign it to yourself.

@dajana212 if you are working on this please let me know, I can assign it to you.

**Comment by Sunnidhya** [comment]
I want to work on this issue. @vishnoianil can you please assign this bug to me?
