### ISSUE TITLE
Logo on login page warps with browser width

### ISSUE THREAD

**Issue by MoralCode** [instructlab/ui#250]
Just opened the Ilab UI and saw this in my narrow browser

![Screenshot_20241007_145503](https://github.com/user-attachments/assets/40dac393-2393-40bc-bd4b-84b8f589f73c)

then made the screen wider:

![Screenshot_20241007_145512](https://github.com/user-attachments/assets/0983870e-c0e7-4031-8777-3883954d8eff)

Seems like it works this way for height too
![Screenshot_20241007_145627](https://github.com/user-attachments/assets/f0aea29b-a8c7-4eea-af91-6f5623fa1817)

it may be better to have both the width and height of the image tied to one browser dimension so they stay in sync and the aspect ratio doesnt change/make it get warped

**Comment by aevo98765** [comment]
@MoralCode here is the PR https://github.com/instructlab/ui/pull/253.

**Comment by vishnoianil** [comment]
> Hmmm, actually this is still reproduceable on the public https://ui.instructlab.ai/login page. has the fix been deployed?

This is not yet deployed in the production. We will deploy it most probably on Wednesday.
