### ISSUE TITLE
Determine a strategy for taxonomy tree placement of submissions

### ISSUE THREAD

**Issue by nerdalert** [instructlab/ui#26]
- Work with triagers to determine where to place UI submissions.
- I think there is consensus that expecting the user to place the submission in a proper directory is generally not ideal. There has been mention in the taxonomy standup that placing the submission could be a triager function.
- We can't do a flat directory since `attribution.txt` is a fixed filename and not referenced in `qna.yml`.

**Comment by vishnoianil** [comment]
PR #85 addresses this issue. It provides a way for user to navigate the taxonomy tree, so that user can choose the directory.
