### ISSUE TITLE
Create openshift manifest for Metrics job or cronjob

### ISSUE THREAD

**Issue by Gregory-Pereira** [instructlab/ui#269]
I suggest that in preparation for enabling users to deploy them stack themselves, that we add a metrics job or cronjob so that we can track who uses it. This will help cover the other side of visibility for those who dont want to use the hosted version.

**Comment by samarpita-bhaumik** [comment]
Please assign this to me

**Comment by Gregory-Pereira** [comment]
Not sure if this helps but I had an example that I had previously implemented in mind: https://github.com/securesign/segment-backup-job. Those are the manifests that could be reused, but wed have to fork it and overwrite the write key, or pass it as an ENV variable, with a contribution there to allow that override. This would be an example of what the manifests would look like: https://github.com/securesign/sigstore-ocp/tree/main/charts/trusted-artifact-signer/templates (see all files starting with `segment-backup`

**Comment by Gregory-Pereira** [comment]
The goal of this issue was to create a method for tracking users self-installing the stack. However, after discussions with the team, it was determined that metrics on self-deploying the stack really fits more with the Productization efforts to capture potential customers for downstream, rather than any upstream concerns. As such, we are going to punt the issue to them, and if they want to implement it they are free to. In the meantime we have Metrics setup for our QA and Prod clusters already setup - and we will focus on figure out what metrics we want to track there.
