### ISSUE TITLE
Add description for skill and knowledge

### ISSUE THREAD

**Issue by cooktheryan** [instructlab/ui#28]
![Screenshot 2024-06-24 at 12 40 11 PM](https://github.com/instructlab/ui/assets/3812500/ac8390a7-4083-4552-9aba-bdb3a61fefcc)

It would be beneficial to users to understand a breakdown of what a knowledge and skill contribution are before choosing which one to submit. I think this could go right below the "Knowledge Contribution Form" or "Skill Contribution Form" that way a new user knows which is the proper one to submit.

**Comment by aevo98765** [comment]
I could take this one. I can't assign issues to myself at the moment though.

**Comment by nerdalert** [comment]
@cooktheryan @aevo98765 ty to you both for this!

**Comment by nerdalert** [comment]
Reolved in #38
