### ISSUE TITLE
Streamline Document Review Process

### ISSUE THREAD

**Issue by mingxzhao** [instructlab/ui#39]
Automatically pull commit information from knowledge document in taxonomy knowledge submission yamls, paste direct link to user created markdown as comment on PR.

**Comment by vishnoianil** [comment]
I think this issue is already address in the recent version of UI. UI uploads the knowledge document to taxonomy-knowledge-docs repo and uses the commit sha in the knowledge yaml file. Closing this issue, but please feel free to re-open it if it's not yet addressed.
