### ISSUE TITLE
[DEVX] Makefile Noise

### ISSUE THREAD

**Issue by Gregory-Pereira** [instructlab/ui#397]
The makefile is getting to be really big which slows down the development experience, looking through ~ 30 targets with similar wording. I suggest we keep 1 makefile in the root of the repo, but then we have a `Makefiles` directory with 1 for each env then import them into the main `Makefile`. It would something like the following:

```bash
$ tree . 
.
├── Makefile
├── Makefiles
│   ├── kind
│   │   └── Makefile
│   ├── qa
│   │   └── Makefile
│   └── prod
│   │   └── Makefile
...
```
Then in the main Makefile we would do:

```bash
$ pwd
.../instructlab/ui
cat Makefile | head -n 10

# Some variables used in all targets
...

include Makefiles/kind/Makefile
include Makefiles/prod/Makefile
include Makefiles/qa/Makefile
```

I imaged 2 more directories, one for the `devcontainer` targets and one for the `linting` targets. Thoughts @vishnoianil?

**Comment by vishnoianil** [comment]
Fixed through #428
