### ISSUE TITLE
Adding dev chat server running instructions

### ISSUE THREAD

**Issue by aevo98765** [instructlab/ui#41]
It would be really useful as a dev contributor if you could quickly spin a model inference server.

Two approaches could be taken here:

1) ilab cli setup and ilab serve instructions - link to existing documentation here.

2) Docker contained service to expose port 8000 and 8001 just in case users have another server running on 8000.

Acceptance Criteria:

- Update https://github.com/instructlab/ui/blob/main/docs/development.md
- add Dockerfile and config.yaml example.
- Optional - push a instructlab serve container to dockerhub for easy running.

**Comment by nerdalert** [comment]
Resolved in #45 🎉
