### ISSUE TITLE
Add dev instructions of how to run the Markdown linter locally

### ISSUE THREAD

**Issue by aevo98765** [instructlab/ui#46]
I made changes to a MD file and found that the CI pipeline failed because of the Markdown linter. I didn't know how to run this locally on my machine which would make it easier to correct these linting issues.

Acceptance Criteria:

Add instructions of what tool and how to install the Markdown linter locally for devs to run checks before pushing remotely.

**Comment by vishnoianil** [comment]
@aevo98765 in the makefile, there is a target `md-lint` that runs the linter locally. That didn't work for you?

**Comment by aevo98765** [comment]
Hey @vishnoianil, ahh I haven't been using the Makefile in this project. Do we think it is worth having instructions of how to run the MD linter outside of the Makefile or just comment to use the Makefile if you want to run the linting checks... or... just close this issue off as not needed?

**Comment by aevo98765** [comment]
https://github.com/instructlab/ui/pull/75
