### ISSUE TITLE
ui started in prod mode doesn't pickup proper styling for download buttons 

### ISSUE THREAD

**Issue by vishnoianil** [instructlab/ui#50]
this is how the button looks like when npm started in prod setting, doesn't happen in dev mode.
<img width="537" alt="Screenshot 2024-07-09 at 11 49 51 AM" src="https://github.com/instructlab/ui/assets/3275433/6e468ed2-3e68-4f62-a656-0b08ce03e182">

**Comment by aevo98765** [comment]
https://github.com/instructlab/ui/pull/54

**Comment by nerdalert** [comment]
ty!
