### ISSUE TITLE
The chat 'Model Selector' defaults back to Granite-7b every time the page is refreshed

### ISSUE THREAD

**Issue by aevo98765** [instructlab/ui#53]
For users that are not using the Granite-7b model for chat inference, every time users visit another page and come back to http://localhost:3000/playground/chat or just refresh the page, the model selector defaults back to Granite-7b. This then causes the chat inference requests to fail because the incorrect model name is passed to the chat model server.

Possible solutions:

- Add the ability for the user to select an option as their default option.
- Model type wont change on a page reset. local web browser storage?
<img width="945" alt="Screenshot 2024-07-10 at 11 10 03" src="https://github.com/instructlab/ui/assets/70710356/9ea41901-5916-4ca5-9336-8e1b51cc30f4">

**Comment by aevo98765** [comment]
Help needed on what the best/preferable approach is to take on this one.

**Comment by nerdalert** [comment]
Can use local storage for sure (or any other thing you prefer). Ty! After we get done with the go live we can tackle a db running.

**Comment by aevo98765** [comment]
https://github.com/instructlab/ui/pull/79

**Comment by vishnoianil** [comment]
Approach proposed in #79 sounds good to me. Once we have a storage hooked up to UI, we can store the last selected model for individual user.
