### ISSUE TITLE
Make changes to the 'Knowledge' section of the 'Knowledge Contribution Form'

### ISSUE THREAD

**Issue by aevo98765** [instructlab/ui#55]
Changes to be made:

1) Change the section name from 'Knowledge' to 'Question and Answers'.

2) Ensure/strongly advise a minimum of 5 Q and As are provided by the user.
`Each qna.yaml file requires a minimum of five question-answer pairs. The qna.yaml format must include the following fields:`
https://github.com/instructlab/taxonomy?tab=readme-ov-file#getting-started-with-knowledge-contributions

3) Encourage the users to add more Q and As to get better synthetically generated data.

4) Reduce the span of the `+ Add Question and Answer` button.

Happy for feedback on this. Also I will split these tasks out into individual issues if this is thought to be better.

**Comment by vishnoianil** [comment]
Yes!, I wanted thinking on the same line as well. I think we need similar changes for the skill as well (I assume there is minimum required for Q&A for skill as well.

**Comment by aevo98765** [comment]
https://github.com/instructlab/ui/pull/95

**Comment by aevo98765** [comment]
Will open a different pull request once #111 is merged.

**Comment by aevo98765** [comment]
Going to wait until UX has advised what to change.
