### ISSUE TITLE
Investigate passing documents to deepsearch

### ISSUE THREAD

**Issue by Gregory-Pereira** [instructlab/ui#56]
Currently we are discussing how we plan to pass the documents to deep-search for conversion. Currently were thinking provide both options for a sending a file as binary data, and having a URL but we need to communicate with Peter and co if this can work.
/cc @nerdalert

**Comment by vishnoianil** [comment]
@Gregory-Pereira We are tracking this work through #137, so is it okay if we close this issue ?
