### ISSUE TITLE
Enhancement: Decide key technology choices to use for UI

### ISSUE THREAD

**Issue by vishnoianil** [instructlab/ui#7]
Current code base uses next.js + typescript. Is this enough for the feature that we would like to deliver? Or do we need to explore some other UI technologies that is require or would prefer to use for building better UI? 

It's good to nail this down, so we have some guidance on what we should use or what we should avoid.

**Comment by toraponibm** [comment]
Here are some thoughts.
1. Next.js + TypeScript is a reasonable choice to go with, given their active development, popularity, and developer base volume.
2. Design framework choice sits on top of that, which we should also agree upon. It consists of design language and guidelines, and actual UI components to use.

As for the second item, candidates include, but not limited to, the following two.
- Carbon Design System: https://carbondesignsystem.com/ 
    + I propose to consider this based on prior experience- it's fairly powerful and versatile, well supported and is known to have emphasis in various aspects such as accessibility.
- PatternFly: https://www.patternfly.org/ 
    + This is used in the initial base code. Is there a particular preference for it?

**Comment by Gregory-Pereira** [comment]
Personally fine with Next.js + Typescript for industry standard stack for UI implementation, and as I have limited experience with design frameworks I will defer to the experts here. However, I would argue that this should be retagged with `release-2.0`. I think we should aim to release something this week to get the tools up and running and then re-factor and implement as we go. We need to get this stuff into the hands of the Triagers + users so people can learn the workflow in time for devconf us (1 month away). I propose that we use this time to take feedback from people and do the redesign. Thoughts?

**Comment by vishnoianil** [comment]
Currently we are settled on Reacht/Next.js/Typescript and go (for backend services). Currently i don't see any alternate proposal regarding these technology choices. Closing this issue at this point of time, but contributors would like to revisit this and brainstorm around the possible options, please feel free to re-open the issue.
