### ISSUE TITLE
Improve the github login UI 

### ISSUE THREAD

**Issue by vishnoianil** [instructlab/ui#76]
Currently the login page has small github icon that takes you for github authentication. This is not very intuitive, folks generally endup trying the github credential in the username/password and it obviously fails. 

We need to either add text "Login with (github icon)" or something better to make it more intuitive.

**Comment by vishnoianil** [comment]
cc @nerdalert

**Comment by Misjohns** [comment]
A few questions:
- Once the user authenticates with GitHub, during future logins can they enter their GitHub Username and Password on the Login screen to open InstructLab? This does not seem to work for me.
- Can we modify the appearance of the login screen once they authenticate with GH?

**Comment by vishnoianil** [comment]
> A few questions:
> 
> * Once the user authenticates with GitHub, during future logins can they enter their GitHub Username and Password on the Login screen to open InstructLab? This does not seem to work for me.

That's good point, i think we can explore this for sure. But in case of account protected with 2 factor authentication, it might still go off the instructlab UI login page to the github page for 2FA. 

> * Can we modify the appearance of the login screen once they authenticate with GH?

@Misjohns Can you share some more details here? After the login, it shows the dashboard. Are you pointing to the changes we discussed in the UI community meeting?
