### ISSUE TITLE
Fix the name of the yaml generated by "Download Yaml"

### ISSUE THREAD

**Issue by vishnoianil** [instructlab/ui#77]
Download yaml feature download the yaml and name it "knowledge_qna.yaml" or "skill_qna.yaml". User needs to rename these files to qna.yaml to submit the PR to taxonomy. It would be better to rename these files qna.yaml, so user doesn't need to rename it  before pushing the PR. Sometime user forgets to rename, and the PR checks fails.

**Comment by vishnoianil** [comment]
cc @nerdalert

**Comment by aevo98765** [comment]
Is this what you are looking for @vishnoianil ->  https://github.com/instructlab/ui/pull/81 ??

**Comment by vishnoianil** [comment]
Issue fixed through #81
