### ISSUE TITLE
Can not chat with the model if it's endpoint url has '/' at the end

### ISSUE THREAD

**Issue by chudegao** [instructlab/ui#84]
Add new model endpoint , if the url has '/' (e.g. http://127.0.0.1:8000/ )at the end, the model can not be chat. 
To avoid this issue, two options:
1. add a check for the text of url, not allow '/' at the end. Or
2. remove '/' if there it's at the end of url .

**Comment by aevo98765** [comment]
https://github.com/instructlab/ui/pull/112

Thanks @chudegao and @MuhammadKurdi-CS for raising and working on this.
