### ISSUE TITLE
Improve InstructLab masthead

### ISSUE THREAD

**Issue by Misjohns** [instructlab/ui#97]
A masthead contains global properties such as logotype, navigation and settings in an organized fashion and it is accessible from all parts of the application. All pages should share a common masthead. The current masthead emphasizes the dark/light mode switcher and logout button. These items are not the primary actions to expose to the user at this level. The masthead should display the following: 
- Show/hide menu
- Logotype
- Help: quick access to documentation, customer support resources, and link to the About modal.  
- User menu: includes an avatar and the username of the currently logged in user. User dropdown includes application settings such as display language, theme, etc., and Log out.

Reference: https://www.patternfly.org/components/masthead/design-guidelines#elements

@beaumorley

**Comment by Misjohns** [comment]
Updated masthead design:
![image](https://github.com/user-attachments/assets/11d050f9-c724-4adc-8475-1c8fb3d6d431)


Updated help and username menus:
![image](https://github.com/user-attachments/assets/bc6f380c-6262-4078-8c15-acd1e8ec0505)

**Comment by Misjohns** [comment]
**Documentation** item should link to: https://github.com/instructlab/instructlab/blob/main/README.md
**Help** item should link to: <TBD>
**About** item opens About modal: [See About modal #102](https://github.com/instructlab/ui/issues/102)

Who can provide me with the appropriate links for Help menu?

**Comment by aevo98765** [comment]
PR to follow but this is what the implementation looks like...

![Screenshot 2024-08-19 at 21 24 41](https://github.com/user-attachments/assets/d5d28b5f-94cf-415f-98cb-69e563c81aec)
![Screenshot 2024-08-19 at 21 25 17](https://github.com/user-attachments/assets/c2d71800-e897-4326-95d0-d7654109e610)
![Screenshot 2024-08-19 at 21 25 23](https://github.com/user-attachments/assets/451d6733-37f1-48ac-be66-8769ef5948de)

**Comment by aevo98765** [comment]
Uploading Masthead-Improvements.mov…

**Comment by aevo98765** [comment]
https://github.com/user-attachments/assets/40f85f31-9cb1-4bcb-b6fa-364af2194348
